import { RelevantData } from "../utils";

const relevantData: RelevantData[] = [
  {
    identifier: "_ACFT_NAME",
    address: 0x0000,
    max_length: 24,
    type: "string",
  },
  {
    identifier: "PLT_KU_DISPLAY",
    address: 0x808c,
    max_length: 22,
    type: "string",
  },
  {
    identifier: "CPG_KU_DISPLAY",
    address: 0x80aa,
    max_length: 22,
    type: "string",
  },
  {
    identifier: "PLT_KU_BRT",
    address: 0x808a,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "CPG_KU_BRT",
    address: 0x80a8,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "PLT_MPD_L_BRT",
    address: 0x8004,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "PLT_MPD_L_VIDEO",
    address: 0x8006,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "PLT_MPD_R_BRT",
    address: 0x8016,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "PLT_MPD_R_VIDEO",
    address: 0x8018,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "CPG_MPD_L_BRT",
    address: 0x800c,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "CPG_MPD_L_VIDEO",
    address: 0x800e,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "CPG_MPD_R_BRT",
    address: 0x801e,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "CPG_MPD_R_VIDEO",
    address: 0x8020,
    mask: 0xffff,
    shift_by: 0,
    max_value: 65535,
    type: "integer",
  },
  {
    identifier: "PLT_MPD_L_MODE",
    address: 0x8008,
    mask: 0x0003,
    shift_by: 0,
    max_value: 2,
    type: "integer",
  },
  {
    identifier: "PLT_MPD_R_MODE",
    address: 0x8014,
    mask: 0x0006,
    shift_by: 1,
    max_value: 2,
    type: "integer",
  },
  {
    identifier: "CPG_MPD_L_MODE",
    address: 0x8010,
    mask: 0x0003,
    shift_by: 0,
    max_value: 2,
    type: "integer",
  },
  {
    identifier: "CPG_MPD_R_MODE",
    address: 0x801c,
    mask: 0x000c,
    shift_by: 2,
    max_value: 2,
    type: "integer",
  },
];

export { relevantData };
