import { RelevantData } from "../utils";

const relevantData: RelevantData[] = [
  {
    indentifier: "PLT_HUD_MODE",
    address: 5258,
    max_length: 1,
    type: "string",
  },
  {
    indentifier: "PLT_STEER_MODE",
    address: 5260,
    max_length: 1,
    type: "string",
  },
  {
    indentifier: "PLT_HUD_DECLUTTER",
    address: 4722,
    mask: 16384,
    shift_by: 14,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_HUD_MODE_AWL",
    address: 4722,
    mask: 32768,
    shift_by: 15,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_VDI_MODE_DISP",
    address: 4722,
    mask: 4096,
    shift_by: 12,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_VDI_MODE_LAND",
    address: 4722,
    mask: 8192,
    shift_by: 13,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_HSD_DIS_MODE",
    address: 4642,
    mask: 384,
    shift_by: 7,
    max_value: 2,
    type: "integer",
  },
  {
    indentifier: "PLT_HSD_ECM_OVER",
    address: 4642,
    mask: 512,
    shift_by: 9,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_VDI_PW_SW",
    address: 4636,
    mask: 32768,
    shift_by: 15,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_HUD_PW_SW",
    address: 4642,
    mask: 1,
    shift_by: 0,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_HSD_PW_SW",
    address: 4642,
    mask: 2,
    shift_by: 1,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_AFCS_PITCH",
    address: 0x120a,
    mask: 0x4000,
    shift_by: 14,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_AFCS_ROLL",
    address: 0x120a,
    mask: 0x8000,
    shift_by: 15,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_AFCS_YAW",
    address: 0x1210,
    mask: 0x0001,
    shift_by: 0,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_AUTOPLT_VECTOR_CARRIER",
    address: 0x1210,
    mask: 0x0006,
    shift_by: 1,
    max_value: 2,
    type: "integer",
  },
  {
    indentifier: "PLT_AUTOPLT_ALT",
    address: 0x1210,
    mask: 0x0008,
    shift_by: 3,
    max_value: 1,
    type: "integer",
  },
  {
    indentifier: "PLT_AUTOPLT_HDG",
    address: 0x1210,
    mask: 0x0030,
    shift_by: 4,
    max_value: 2,
    type: "integer",
  },
  {
    indentifier: "PLT_AUTOPLT_ENGAGE",
    address: 0x1210,
    mask: 0x0040,
    shift_by: 6,
    max_value: 1,
    type: "integer",
  },
];

export { relevantData };
